name: Deploy to App Engine
on: [ workflow_dispatch ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#      - run: sudo apt install git-crypt
      - uses: actions/checkout@v2
        with:
          repository: cl-ssi/config
      - run: |
          ls ${{ github.workspace }}
#      - uses: google-github-actions/deploy-appengine@v0.4.0
#        with:
#          deliverables: unisalud-test.yaml
