name: Deploy to App Engine
on: [ workflow_dispatch ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install git-crypt
      - run: echo "${{ secrets.CRYPT_KEY_CONFIG_REPO }}" > config/config-git-crypt.key
      - run: git-crypt unlock config/config-git-crypt.key
      - uses: actions/checkout@v2
        with:
          repository: cl-ssi/config
          token: ${{ secrets.CONFIG_REPO_TOKEN }}
          path: config
      - run: |
          ls ${{ github.workspace }}

      - run: |
          ls ${{ github.workspace }}/config
#      - uses: google-github-actions/deploy-appengine@v0.4.0
#        with:
#          deliverables: unisalud-test.yaml
