name: Deploy to App Engine
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
